In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.23.2 in C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("C:\\Users\\Dell\\Downloads\\22. messy_sales_data.csv")

In [4]:
sd = df.copy()

In [5]:
sd.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [6]:
sd.tail()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
106570,ORD49057,CUST01636,MAX OM,chennai,FURNITURE,debit card,Rs.1961.37,4.0,0,5.0,2023-06-11,32.0,max.om@outlook.com,9123457578,Amazing quality!!!
106571,ORD60012,CUST01826,CHARAN MANNE,pune,Toys,Cash on Delivery,Rs.1468.22,2.0,20,3.3,22 Apr 2024,43.0,charan.manne@yahoo.com,9226831132,Good product loved it
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,11/09/2024,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality
106573,ORD68225,CUST04602,Ladli Nazareth,AHMEDABAD,electronic,DEBIT CARD,916.52,1.0,25,4.6,19/12/2024,50.0,NaN,9914721436,NaN
106574,ORD72531,CUST07969,Yatin Rao,Chennai,Sport,DEBIT CARD,891.46,2.0,5,4.3,2024-09-29,32.0,yatin.rao@gmail.com,9438589142,Superb!!! fast delivery

In [7]:
sd.shape

(106575, 15)

In [8]:
sd.size

1598625

In [9]:
sd.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'City', 'Category',
       'PaymentMode', 'Price', 'Quantity', 'DiscountPct', 'Rating',
       'OrderDate', 'CustomerAge', 'Email', 'Phone', 'ReviewText'],
      dtype='object')

In [10]:
sd.dtypes

OrderID          object
CustomerID       object
CustomerName     object
City             object
Category         object
PaymentMode      object
Price            object
Quantity        float64
DiscountPct       int64
Rating          float64
OrderDate        object
CustomerAge     float64
Email            object
Phone            object
ReviewText       object
dtype: object

In [11]:
sd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106575 entries, 0 to 106574
Data columns (total 15 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   OrderID       106575 non-null  object
 1   CustomerID    106575 non-null  object
 2   CustomerName  106575 non-null  object
 3   City          104481 non-null  object
 4   Category      106575 non-null  object
 5   PaymentMode   103332 non-null  object
 6   Price         106575 non-null  object
 7   Quantity      106575 non-null  float64
 8   DiscountPct   106575 non-null  int64
 9   Rating        100129 non-null  float64
 10  OrderDate     102358 non-null  object
 11  CustomerAge   106575 non-null  float64
 12  Email         99176 non-null   object
 13  Phone         98117 non-null   object
 14  ReviewText    93200 non-null   object
dtypes: float64(3), int64(1), object(11)
memory usage: 12.2+ MB

In [12]:
sd.isnull().sum()

OrderID             0
CustomerID          0
CustomerName        0
City             2094
Category            0
PaymentMode      3243
Price               0
Quantity            0
DiscountPct         0
Rating           6446
OrderDate        4217
CustomerAge         0
Email            7399
Phone            8458
ReviewText      13375
dtype: int64

In [13]:
sd.isna().sum()

OrderID             0
CustomerID          0
CustomerName        0
City             2094
Category            0
PaymentMode      3243
Price               0
Quantity            0
DiscountPct         0
Rating           6446
OrderDate        4217
CustomerAge         0
Email            7399
Phone            8458
ReviewText      13375
dtype: int64

In [14]:
sd.isnull().sum().sum()

45232

In [16]:
sd.describe()

            Quantity    DiscountPct         Rating    CustomerAge
count  106575.000000  106575.000000  100129.000000  106575.000000
mean        2.066817       9.382125       3.409874      39.678893
std         1.387769       9.176865       1.306731      19.263288
min        -5.000000       0.000000       0.500000       0.000000
25%         1.000000       0.000000       2.600000      28.000000
50%         2.000000      10.000000       3.300000      38.000000
75%         3.000000      20.000000       4.100000      47.000000
max         5.000000      25.000000       9.900000     150.000000

In [17]:
sd.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
OrderID,106575,105000,ORD17079,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerID,106575,9000,CUST01057,27,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerName,106575,37440,Charvi Dara,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,104481,56,hyderabad,2652,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,106575,35,BEAUTY,4499,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaymentMode,103332,24,UPI,5184,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Price,106575,88579,966.86,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,106575.0,NaN,NaN,NaN,2.066817,1.387769,-5.0,1.0,2.0,3.0,5.0
DiscountPct,106575.0,NaN,NaN,NaN,9.382125,9.176865,0.0,0.0,10.0,20.0,25.0
Rating,100129.0,NaN,NaN,NaN,3.409874,1.306731,0.5,2.6,3.3,4.1,9.9
OrderDate,102358,3367,01/03/2024,82,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CustomerAge,106575.0,NaN,NaN,NaN,39.678893,19.263288,0.0,28.0,38.0,47.0,150.0
Email,99176,39350,chakradhar.venkataraman@rediffmail.com,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Phone,98117,96653,9363299083,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ReviewText,93200,14,worst product ever received damaged item,6785,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
type(sd.City)

pandas.core.series.Series

In [19]:
sd.City

0         bangalore
1             DELHI
2           chennai
3           Jaipur
4           Amdavad
            ...
106570      chennai
106571         pune
106572        DELHI
106573    AHMEDABAD
106574      Chennai
Name: City, Length: 106575, dtype: object

In [20]:
type(sd[["City", "Price", "Category"]])

pandas.core.frame.DataFrame

In [21]:
sd[["City", "Price", "Category"]]

             City       Price    Category
0       bangalore      904.48     Grocery
1           DELHI     1823.76      SPORTS
2         chennai      770.67  electronic
3         Jaipur      2028.06    Clothing
4         Amdavad      604.00   FURNITURE
...           ...         ...         ...
106570    chennai  Rs.1961.37   FURNITURE
106571       pune  Rs.1468.22        Toys
106572      DELHI      414.94   Furniture
106573  AHMEDABAD      916.52  electronic
106574    Chennai      891.46       Sport

[106575 rows x 3 columns]

In [22]:
sd["City"].value_counts()

City
hyderabad     2652
Jaipur        2651
JAIPUR        2635
LUCKNOW       2634
Jaipur        2631
 Hyderabad    2628
 Lucknow      2602
Hyderabad     2585
Lucknow       2575
jaipur        2569
HYDERABAD     2562
lucknow       2547
Ahmedabad     2134
Poona         2129
pune          2124
Amdavad       2110
Pune          2093
PUNE          2086
ahmedabad     2085
amdavad       2082
poona         2012
AHMEDABAD     1994
CALCUTTA      1833
madras        1816
Madras        1807
chennai       1805
Calcutta      1792
Chennai       1791
Kolkata       1755
KOLKATA       1753
kolkata       1739
CHENNAI       1728
calcutta      1672
MADRAS        1663
banglore      1557
bangalore     1549
New Delhi     1526
Bangalore     1517
NEW DELHI     1517
bengaluru     1488
BANGALORE     1481
new delhi     1473
Bengaluru     1462
DELHI         1456
delhi         1448
Delhi         1444
Banglore      1436
 Delhi        1396
BOMBAY        1362
Mumbai        1339
mumbai        1315
 Mumbai       1300
bombay        1298
mumbai        1296
MUMBAI        1281
Bombay        1266
Name: count, dtype: int64

In [23]:
sd["Category"].nunique()

35

In [24]:
sd["Category"].unique()

array(['Grocery', 'SPORTS', 'electronic', 'Clothing', 'FURNITURE',
       'CLOTHING', 'BEAUTY', 'Furnitures', 'Clothings', 'electronics',
       'Beauty', 'TOYS', 'sports', 'beauty', 'grocery', 'Book', 'Sports',
       'Groceries', 'Electronics', 'book', 'Books', 'GROCERY',
       'Clothing ', 'books', 'furniture', 'ELECTRONICS', 'Furniture',
       'clothing', 'Toys', 'Electronic', 'toys', 'Toy', 'BOOKS', 'toy',
       'Sport'], dtype=object)

In [25]:
sd["Category"].value_counts()

Category
BEAUTY         4499
Beauty         4429
beauty         4380
furniture      3464
SPORTS         3401
sports         3345
GROCERY        3331
FURNITURE      3314
Furnitures     3312
Grocery        3307
Furniture      3303
grocery        3299
Sports         3294
Groceries      3268
Sport          3250
electronic     2806
toys           2802
Toy            2747
CLOTHING       2723
ELECTRONICS    2712
Clothings      2695
Clothing       2695
Book           2684
BOOKS          2671
Clothing       2670
clothing       2657
books          2656
book           2655
Electronic     2654
TOYS           2646
toy            2622
Books          2590
Electronics    2588
electronics    2565
Toys           2541
Name: count, dtype: int64

In [26]:
sd.duplicated().sum()

1056

In [27]:
sd.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [28]:
sd["total_sales"] = df['Rating']*df["Quantity"]

In [29]:
sd["col1"] = sd["PaymentMode"]

In [31]:
sd.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,total_sales,col1
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad,9.9,net_banking
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service,20.0,Net Banking
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product,4.9,Upi
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN,2.9,COD
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery,14.8,cc

In [32]:
sd.sample(5)

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,total_sales,col1
98658,ORD95654,CUST00593,Chandani Soman,NEW DELHI,Sport,debit card,"₹1,168.64",4.0,20,3.3,15 Sep 2024,44.0,chandani.soman@hotmail.com,+91-9165648367,Superb!!! fast delivery,13.2,debit card
39234,ORD82600,CUST06186,Yash Kibe,Banglore,Furniture,credit_card,192.72,1.0,10,4.2,13-09-2023,28.0,yash.kibe@yahoo.com,9122486993,Not satisfied poor quality,4.2,credit_card
85749,ORD94152,CUST07905,Nilima Bhargava,poona,Books,cod,3195.45,1.0,20,1.2,04/03/2024,52.0,nilima.bhargava@gmail.com,9646836608,Superb!!! fast delivery,1.2,cod
46477,ORD1863,CUST00900,Isaiah Khosla,NaN,Electronics,DC,-1108.24,4.0,0,4.0,03/11/2024,27.0,isaiah.khosla@yahoo.com,9312845035,Good product loved it,16.0,DC
70346,ORD64700,CUST04951,Nidra Chhabra,lucknow,grocery,net_banking,896.51,2.0,20,3.4,04/20/2024,41.0,nidra.chhabra@outlook.com,9524149972,Packaging was bad,6.8,net_banking

In [33]:
sd.drop("col1", axis = 1)

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,total_sales
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad,9.9
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service,20.0
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product,4.9
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN,2.9
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery,14.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106570,ORD49057,CUST01636,MAX OM,chennai,FURNITURE,debit card,Rs.1961.37,4.0,0,5.0,2023-06-11,32.0,max.om@outlook.com,9123457578,Amazing quality!!!,20.0
106571,ORD60012,CUST01826,CHARAN MANNE,pune,Toys,Cash on Delivery,Rs.1468.22,2.0,20,3.3,22 Apr 2024,43.0,charan.manne@yahoo.com,9226831132,Good product loved it,6.6
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,11/09/2024,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality,6.6
106573,ORD68225,CUST04602,Ladli Nazareth,AHMEDABAD,electronic,DEBIT CARD,916.52,1.0,25,4.6,19/12/2024,50.0,NaN,9914721436,NaN,4.6
106574,ORD72531,CUST07969,Yatin Rao,Chennai,Sport,DEBIT CARD,891.46,2.0,5,4.3,2024-09-29,32.0,yatin.rao@gmail.com,9438589142,Superb!!! fast delivery,8.6

In [34]:
sd.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,total_sales,col1
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad,9.9,net_banking
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service,20.0,Net Banking
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product,4.9,Upi
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN,2.9,COD
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery,14.8,cc

In [35]:
df1 = sd.drop("col1", axis = 1)

In [36]:
df1.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText,total_sales
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad,9.9
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service,20.0
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product,4.9
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN,2.9
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery,14.8

In [37]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [38]:
df.drop("col1", axis = 1, inplace=True)

KeyError: "['col1'] not found in axis"

In [40]:
df.head

<bound method NDFrame.head of          OrderID CustomerID          CustomerName       City    Category  \
0       ORD51058  CUST04879        Chaitanya Mane  bangalore     Grocery
1       ORD70248  CUST00177         Siddharth Sha      DELHI      SPORTS
2       ORD43804  CUST04537  Nathaniel Chatterjee    chennai  electronic
3       ORD46367  CUST07605     pranit contractor    Jaipur     Clothing
4       ORD32922  CUST03180    Hemang Chakraborty    Amdavad   FURNITURE
...          ...        ...                   ...        ...         ...
106570  ORD49057  CUST01636              MAX OM      chennai   FURNITURE
106571  ORD60012  CUST01826          CHARAN MANNE       pune        Toys
106572  ORD78050  CUST04033           Isaiah Wali      DELHI   Furniture
106573  ORD68225  CUST04602      Ladli Nazareth    AHMEDABAD  electronic
106574  ORD72531  CUST07969             Yatin Rao    Chennai       Sport

             PaymentMode       Price  Quantity  DiscountPct  Rating  \
0            net_banking      904.48       3.0           10     3.3
1            Net Banking     1823.76       4.0           20     5.0
2                    Upi      770.67       1.0            0     4.9
3                    COD     2028.06       1.0            0     2.9
4                     cc      604.00       4.0           10     3.7
...                  ...         ...       ...          ...     ...
106570        debit card  Rs.1961.37       4.0            0     5.0
106571  Cash on Delivery  Rs.1468.22       2.0           20     3.3
106572        Debit Card      414.94       2.0           10     3.3
106573        DEBIT CARD      916.52       1.0           25     4.6
106574        DEBIT CARD      891.46       2.0            5     4.3

          OrderDate  CustomerAge                             Email  \
0        2023-04-24         29.0          chaitanya.mane@gmail.com
1        04-01-2023         38.0                               NaN
2        11/17/2024         40.0  nathaniel.chatterjee@outlook.com
3               NaN         41.0  pranit.contractor@rediffmail.com
4       14 Jan 2023         44.0    hemang.chakraborty@outlook.com
...             ...          ...                               ...
106570   2023-06-11         32.0                max.om@outlook.com
106571  22 Apr 2024         43.0            charan.manne@yahoo.com
106572   11/09/2024         23.0           isaiah.wali@hotmail.com
106573   19/12/2024         50.0                               NaN
106574   2024-09-29         32.0               yatin.rao@gmail.com

             Phone                   ReviewText
0       9454663439            Packaging was bad
1              NaN              great service
2       9573975601              Okayish product
3       9235766629                          NaN
4       9731250657      Superb!!! fast delivery
...            ...                          ...
106570  9123457578           Amazing quality!!!
106571  9226831132        Good product loved it
106572  9758098090  Not satisfied  poor quality
106573  9914721436                          NaN
106574  9438589142      Superb!!! fast delivery

[106575 rows x 15 columns]>