In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("C:\\Users\\Dell\\Downloads\\22. messy_sales_data.csv")

In [3]:
df = df1.copy()

In [4]:
df['City'].unique()

array(['bangalore', 'DELHI', 'chennai', 'Jaipur ', 'Amdavad', 'New Delhi',
       'new delhi', 'Kolkata', 'hyderabad', 'mumbai', ' Lucknow',
       'LUCKNOW', 'jaipur', 'Bengaluru', 'Calcutta', 'MADRAS',
       'bengaluru', 'Bombay', 'Poona', 'CHENNAI', 'pune', 'CALCUTTA',
       'Lucknow', 'kolkata', 'AHMEDABAD', ' Mumbai', 'Ahmedabad', 'PUNE',
       'Jaipur', 'delhi', 'KOLKATA', 'Mumbai', nan, ' Delhi ',
       'HYDERABAD', 'calcutta', 'bombay', 'amdavad', 'NEW DELHI',
       'JAIPUR', 'ahmedabad', 'poona', 'Madras', 'Bangalore', 'Chennai',
       'lucknow', 'Banglore', 'madras', 'BANGALORE', 'mumbai  ',
       'Hyderabad', 'BOMBAY', 'Pune', 'Delhi', 'banglore', ' Hyderabad',
       'MUMBAI'], dtype=object)

In [5]:
df['City']= df['City'].str.strip().str.lower()

In [6]:
df['City'].unique()

array(['bangalore', 'delhi', 'chennai', 'jaipur', 'amdavad', 'new delhi',
       'kolkata', 'hyderabad', 'mumbai', 'lucknow', 'bengaluru',
       'calcutta', 'madras', 'bombay', 'poona', 'pune', 'ahmedabad', nan,
       'banglore'], dtype=object)

In [7]:
city_map = {
    'mumbai': 'Mumbai', 'bombay': 'Mumbai',
    'delhi': 'Delhi', 'new delhi': 'Delhi',
    'bangalore': 'Bangalore', 'bengaluru': 'Bangalore', 'banglore': 'Bangalore',
    'chennai': 'Chennai', 'madras': 'Chennai',
    'kolkata': 'Kolkata', 'calcutta': 'Kolkata',
    'hyderabad': 'Hyderabad',
    'pune': 'Pune', 'poona': 'Pune',
    'ahmedabad': 'Ahmedabad', 'amdavad': 'Ahmedabad',
    'jaipur': 'Jaipur',
    'lucknow': 'Lucknow',
    'unknown': 'Unknown'
}

In [8]:
df['City']= df['City'].map(city_map).fillna(df["City"].str.title())

In [9]:
df['City'].unique()

array(['Bangalore', 'Delhi', 'Chennai', 'Jaipur', 'Ahmedabad', 'Kolkata',
       'Hyderabad', 'Mumbai', 'Lucknow', 'Pune', nan], dtype=object)

In [10]:
df["City"].isnull().sum()

2094

In [11]:
df["City"].mode()

0    Chennai
Name: City, dtype: object

In [12]:
df["City"] = df["City"].fillna(df["City"].mode())

In [13]:
df["City"].isnull().sum()

2094

In [14]:
df["City"].unique()

array(['Bangalore', 'Delhi', 'Chennai', 'Jaipur', 'Ahmedabad', 'Kolkata',
       'Hyderabad', 'Mumbai', 'Lucknow', 'Pune', nan], dtype=object)

In [15]:
df["City"] = df["City"].fillna('Chennai')

In [16]:
df["City"].unique()

array(['Bangalore', 'Delhi', 'Chennai', 'Jaipur', 'Ahmedabad', 'Kolkata',
       'Hyderabad', 'Mumbai', 'Lucknow', 'Pune'], dtype=object)

In [17]:
df["City"].isnull().sum()

0

In [18]:
df["City"].unique()

array(['Bangalore', 'Delhi', 'Chennai', 'Jaipur', 'Ahmedabad', 'Kolkata',
       'Hyderabad', 'Mumbai', 'Lucknow', 'Pune'], dtype=object)

In [19]:
df["Category"].unique()

array(['Grocery', 'SPORTS', 'electronic', 'Clothing', 'FURNITURE',
       'CLOTHING', 'BEAUTY', 'Furnitures', 'Clothings', 'electronics',
       'Beauty', 'TOYS', 'sports', 'beauty', 'grocery', 'Book', 'Sports',
       'Groceries', 'Electronics', 'book', 'Books', 'GROCERY',
       'Clothing ', 'books', 'furniture', 'ELECTRONICS', 'Furniture',
       'clothing', 'Toys', 'Electronic', 'toys', 'Toy', 'BOOKS', 'toy',
       'Sport'], dtype=object)

In [20]:
df.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'City', 'Category',
       'PaymentMode', 'Price', 'Quantity', 'DiscountPct', 'Rating',
       'OrderDate', 'CustomerAge', 'Email', 'Phone', 'ReviewText'],
      dtype='object')

In [21]:
for col in df.columns:
    print()
    print( f"------------------column name {col}------------------")
    print(df[col].unique())
    print("==="*30)
    print()

------------------column name OrderID------------------
['ORD51058' 'ORD70248' 'ORD43804' ... 'ORD78050' 'ORD68225' 'ORD72531']
==========================================================================================


------------------column name CustomerID------------------
['CUST04879' 'CUST00177' 'CUST04537' ... 'CUST00727' 'CUST03384'
 'CUST07869']
==========================================================================================


------------------column name CustomerName------------------
['Chaitanya Mane' 'Siddharth Sha' 'Nathaniel Chatterjee' ... ' Jack Dara'
 'ATHARV LAD' '  MAX OM  ']
==========================================================================================


------------------column name City------------------
['Bangalore' 'Delhi' 'Chennai' 'Jaipur' 'Ahmedabad' 'Kolkata' 'Hyderabad'
 'Mumbai' 'Lucknow' 'Pune']
==========================================================================================


------------------column name Category------------------
['Grocery' 'SPORTS' 'electronic' 'Clothing' 'FURNITURE' 'CLOTHING'
 'BEAUTY' 'Furnitures' 'Clothings' 'electronics' 'Beauty' 'TOYS' 'sports'
 'beauty' 'grocery' 'Book' 'Sports' 'Groceries' 'Electronics' 'book'
 'Books' 'GROCERY' 'Clothing ' 'books' 'furniture' 'ELECTRONICS'
 'Furniture' 'clothing' 'Toys' 'Electronic' 'toys' 'Toy' 'BOOKS' 'toy'
 'Sport']
==========================================================================================


------------------column name PaymentMode------------------
['net_banking' 'Net Banking' 'Upi' 'COD' 'cc' 'Debit Card' 'credit_card'
 'Cash on Delivery' 'net banking' 'NET BANKING' nan 'dc'
 'cash on delivery' 'Credit Card' 'DC' 'CREDIT CARD' 'Netbanking'
 'DEBIT CARD' 'UPI ' 'debit card' 'cod' 'UPI' 'upi' 'CC' 'credit card']
==========================================================================================


------------------column name Price------------------
['904.48' '1823.76' '770.67' ... '₹1,854.93' 'Rs.1961.37' 'Rs.1468.22']
==========================================================================================


------------------column name Quantity------------------
[ 3.  4.  1.  2. -2.  5. -5. -1. -3. -4.]
==========================================================================================


------------------column name DiscountPct------------------
[10 20  0  5 25 15]
==========================================================================================


------------------column name Rating------------------
[3.3 5.  4.9 2.9 3.7 2.8 nan 2.4 1.1 1.9 4.5 1.8 3.2 1.7 3.4 3.  2.1 4.8
 3.1 3.5 3.6 1.6 2.2 0.5 3.9 1.3 4.1 4.  1.4 2.6 4.4 4.6 4.7 4.3 2.5 2.3
 5.6 0.8 2.  1.5 7.8 3.8 0.7 2.7 0.9 4.2 1.2 9.4 9.3 8.  0.6 8.9 1.  8.1
 7.6 9.6 6.8 7.1 8.3 5.8 5.5 7.  7.9 6.4 9.2 8.2 8.7 8.5 7.7 6.1 9.5 7.3
 6.2 9.8 7.2 5.9 9.9 5.7 9.  6.7 6.5 6.6 6.  8.6 6.3 7.5 9.1 8.8 9.7 8.4
 6.9 7.4]
==========================================================================================


------------------column name OrderDate------------------
['2023-04-24' '04-01-2023' '11/17/2024' ... '2024-05-30' '30 Jul 2024'
 '2024-12-19']
==========================================================================================


------------------column name CustomerAge------------------
[ 29.  38.  40.  41.  44.  32.  34.  43.  36.  69.  42.  56.  22.  39.
 133.  37.  26.  30.  35.  46.  31.  48.  49.  18.  47.  50.  53.  57.
  54.  23. 139.  45.  64.  51.   8.  25.  55.  27.  60.  24. 120.  52.
   0.  28.  63.  58.   5.  59.  21.  20.  66.  70.  19.  33. 150.  62.
  65.  68. 105.  61.  67.  73.  75.  72.  71.  74.]
==========================================================================================


------------------column name Email------------------
['chaitanya.mane@gmail.com' nan 'nathaniel.chatterjee@outlook.com' ...
 'mahika.jha@rediffmail.com' 'ekiya.kar@rediffmail.com'
 'kevin.gokhale@rediffmail.com']
==========================================================================================


------------------column name Phone------------------
['9454663439' nan '9573975601' ... '9758098090' '9914721436' '9438589142']
==========================================================================================


------------------column name ReviewText------------------
['Packaging was bad' '  great service  ' 'Okayish product' nan
 'Superb!!! fast delivery' 'delivery was late'
 'worst product ever received damaged item' 'Average experience'
 'Not satisfied  poor quality' 'value for money' 'Good product loved it'
 'Excellent!!! will buy again' 'Will not recommend' 'Product as described'
 'Amazing quality!!!']
==========================================================================================

In [22]:
df['Category'].unique()

array(['Grocery', 'SPORTS', 'electronic', 'Clothing', 'FURNITURE',
       'CLOTHING', 'BEAUTY', 'Furnitures', 'Clothings', 'electronics',
       'Beauty', 'TOYS', 'sports', 'beauty', 'grocery', 'Book', 'Sports',
       'Groceries', 'Electronics', 'book', 'Books', 'GROCERY',
       'Clothing ', 'books', 'furniture', 'ELECTRONICS', 'Furniture',
       'clothing', 'Toys', 'Electronic', 'toys', 'Toy', 'BOOKS', 'toy',
       'Sport'], dtype=object)

In [23]:
df['Category'] = df['Category'].str.strip().str.lower().str.rstrip("s")

In [24]:
df['Category'].unique()

array(['grocery', 'sport', 'electronic', 'clothing', 'furniture',
       'beauty', 'toy', 'book', 'grocerie'], dtype=object)

In [25]:
df['Category'] = df['Category'].str.replace('grocerie','grocery' )

In [26]:
df['Category'].unique()

array(['grocery', 'sport', 'electronic', 'clothing', 'furniture',
       'beauty', 'toy', 'book'], dtype=object)

In [27]:
df['Category'].isnull().sum()

0

In [29]:
df['Category'] = df['Category'].str.title()
df['Category'].unique()

array(['Grocery', 'Sport', 'Electronic', 'Clothing', 'Furniture',
       'Beauty', 'Toy', 'Book'], dtype=object)

In [30]:
df['PaymentMode'].unique()

array(['net_banking', 'Net Banking', 'Upi', 'COD', 'cc', 'Debit Card',
       'credit_card', 'Cash on Delivery', 'net banking', 'NET BANKING',
       nan, 'dc', 'cash on delivery', 'Credit Card', 'DC', 'CREDIT CARD',
       'Netbanking', 'DEBIT CARD', 'UPI ', 'debit card', 'cod', 'UPI',
       'upi', 'CC', 'credit card'], dtype=object)

In [31]:
payment_map = {
    'credit card':'Credit Card', 'cc':'Credit Card', 'credit_card':'Credit Card',
    'debit card':'Debit Card', 'dc':'Debit Card',
    'upi':'UPI',
    'cod':'Cash on Delivery', 'cash on delivery':'Cash on Delivery',
    'net banking':'Net Banking', 'netbanking':'Net Banking', 'net_banking':'Net Banking'
}

In [32]:
df['PaymentMode'] = df['PaymentMode'].str.strip().str.lower().map(payment_map)

In [33]:
df['PaymentMode'].unique()

array(['Net Banking', 'UPI', 'Cash on Delivery', 'Credit Card',
       'Debit Card', nan], dtype=object)

In [34]:
df['PaymentMode'].isnull().sum()

3243

In [35]:
df['PaymentMode'].mode()[0]

'Net Banking'

In [36]:
df['PaymentMode']= df['PaymentMode'].fillna(df['PaymentMode'].mode()[0])

In [37]:
df['PaymentMode'].isnull().sum()

0

In [38]:
df['Price'].unique()

array(['904.48', '1823.76', '770.67', ..., '₹1,854.93', 'Rs.1961.37',
       'Rs.1468.22'], dtype=object)

In [39]:
type(df['Price'])

pandas.core.series.Series

In [40]:
df['Price'].dtypes

dtype('O')

In [41]:
df["Price"].astype("int")

ValueError: invalid literal for int() with base 10: '904.48'

In [42]:
df["Price"] = df["Price"].str.strip().str.replace("₹", "")

In [43]:
df["Price"].unique()

array(['904.48', '1823.76', '770.67', ..., '1,854.93', 'Rs.1961.37',
       'Rs.1468.22'], dtype=object)

In [44]:
df["Price"] = df["Price"].str.replace("Rs.", "")

In [45]:
df["Price"].unique()

array(['904.48', '1823.76', '770.67', ..., '1,854.93', '1961.37',
       '1468.22'], dtype=object)

In [46]:
df["Price"] = df["Price"].str.replace("-", "")

In [47]:
df["Price"].unique()

array(['904.48', '1823.76', '770.67', ..., '1,854.93', '1961.37',
       '1468.22'], dtype=object)

In [48]:
df["Price"].dtypes

dtype('O')

In [49]:
df["Price"] = df["Price"].str.replace(",", "")

In [50]:
df["Price"] = df["Price"].astype("float64")

In [51]:
df.dtypes

OrderID          object
CustomerID       object
CustomerName     object
City             object
Category         object
PaymentMode      object
Price           float64
Quantity        float64
DiscountPct       int64
Rating          float64
OrderDate        object
CustomerAge     float64
Email            object
Phone            object
ReviewText       object
dtype: object

In [52]:
df["Quantity"].unique()

array([ 3.,  4.,  1.,  2., -2.,  5., -5., -1., -3., -4.])

In [53]:
df["Quantity"] = df["Quantity"].abs()

In [54]:
df["Quantity"].unique()

array([3., 4., 1., 2., 5.])

In [55]:
df["Quantity"] = df["Quantity"].astype("int64")

In [56]:
df['Rating']

0         3.3
1         5.0
2         4.9
3         2.9
4         3.7
         ...
106570    5.0
106571    3.3
106572    3.3
106573    4.6
106574    4.3
Name: Rating, Length: 106575, dtype: float64

In [57]:
df['Rating'].describe()

count    100129.000000
mean          3.409874
std           1.306731
min           0.500000
25%           2.600000
50%           3.300000
75%           4.100000
max           9.900000
Name: Rating, dtype: float64

In [58]:
df['Rating'].unique()

array([3.3, 5. , 4.9, 2.9, 3.7, 2.8, nan, 2.4, 1.1, 1.9, 4.5, 1.8, 3.2,
       1.7, 3.4, 3. , 2.1, 4.8, 3.1, 3.5, 3.6, 1.6, 2.2, 0.5, 3.9, 1.3,
       4.1, 4. , 1.4, 2.6, 4.4, 4.6, 4.7, 4.3, 2.5, 2.3, 5.6, 0.8, 2. ,
       1.5, 7.8, 3.8, 0.7, 2.7, 0.9, 4.2, 1.2, 9.4, 9.3, 8. , 0.6, 8.9,
       1. , 8.1, 7.6, 9.6, 6.8, 7.1, 8.3, 5.8, 5.5, 7. , 7.9, 6.4, 9.2,
       8.2, 8.7, 8.5, 7.7, 6.1, 9.5, 7.3, 6.2, 9.8, 7.2, 5.9, 9.9, 5.7,
       9. , 6.7, 6.5, 6.6, 6. , 8.6, 6.3, 7.5, 9.1, 8.8, 9.7, 8.4, 6.9,
       7.4])

In [59]:
df['Rating'] = pd.to_numeric(df['Rating'],errors= 'coerce')

In [60]:
df['Rating'].unique()

array([3.3, 5. , 4.9, 2.9, 3.7, 2.8, nan, 2.4, 1.1, 1.9, 4.5, 1.8, 3.2,
       1.7, 3.4, 3. , 2.1, 4.8, 3.1, 3.5, 3.6, 1.6, 2.2, 0.5, 3.9, 1.3,
       4.1, 4. , 1.4, 2.6, 4.4, 4.6, 4.7, 4.3, 2.5, 2.3, 5.6, 0.8, 2. ,
       1.5, 7.8, 3.8, 0.7, 2.7, 0.9, 4.2, 1.2, 9.4, 9.3, 8. , 0.6, 8.9,
       1. , 8.1, 7.6, 9.6, 6.8, 7.1, 8.3, 5.8, 5.5, 7. , 7.9, 6.4, 9.2,
       8.2, 8.7, 8.5, 7.7, 6.1, 9.5, 7.3, 6.2, 9.8, 7.2, 5.9, 9.9, 5.7,
       9. , 6.7, 6.5, 6.6, 6. , 8.6, 6.3, 7.5, 9.1, 8.8, 9.7, 8.4, 6.9,
       7.4])

In [61]:
(df['Rating'] < 0 )

0         False
1         False
2         False
3         False
4         False
          ...
106570    False
106571    False
106572    False
106573    False
106574    False
Name: Rating, Length: 106575, dtype: bool

In [62]:
(df['Rating'] > 5)

0         False
1         False
2         False
3         False
4         False
          ...
106570    False
106571    False
106572    False
106573    False
106574    False
Name: Rating, Length: 106575, dtype: bool

In [63]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,Bangalore,Grocery,Net Banking,904.48,3,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,Delhi,Sport,Net Banking,1823.76,4,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,Chennai,Electronic,UPI,770.67,1,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,Cash on Delivery,2028.06,1,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Ahmedabad,Furniture,Credit Card,604.00,4,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [64]:
df.loc[0:100000:10000,["City", "Price", "OrderID"]]

             City    Price   OrderID
0       Bangalore   904.48  ORD51058
10000   Hyderabad  1163.12   ORD5068
20000   Hyderabad   515.60  ORD94030
30000       Delhi   405.97  ORD92683
40000   Bangalore  1377.23  ORD84537
50000       Delhi  1457.76  ORD94939
60000     Kolkata   633.14  ORD54005
70000     Chennai  1554.58  ORD52725
80000     Lucknow  1063.18   ORD4063
90000     Chennai   503.94  ORD12862
100000  Hyderabad  1407.61  ORD48867

In [65]:
df.iloc[0::5000, 0::3]

         OrderID       City    Price  Rating                          Email
0       ORD51058  Bangalore   904.48     3.3       chaitanya.mane@gmail.com
5000    ORD79486       Pune   704.69     3.5   yashawini.raj@rediffmail.com
10000    ORD5068  Hyderabad  1163.12     1.3   krishna.morar@rediffmail.com
15000   ORD75165  Bangalore  1098.29     3.4       bhavani.devi@hotmail.com
20000   ORD94030  Hyderabad   515.60     3.4       elijah.mitra@hotmail.com
25000   ORD46339    Kolkata  1207.32     3.6       anmol.chadha@outlook.com
30000   ORD92683      Delhi   405.97     2.2           jhalak.rau@yahoo.com
35000   ORD41431       Pune   398.51     4.0       chaman.lalla@hotmail.com
40000   ORD84537  Bangalore  1377.23     3.6                            NaN
45000   ORD78382  Bangalore  5539.55     1.6         arya.shere@outlook.com
50000   ORD94939      Delhi  1457.76     3.6   hemangini.pandey@hotmail.com
55000   ORD12839       Pune  1365.90     1.5      pavani.chandran@gmail.com
60000   ORD54005    Kolkata   633.14     1.7     jalsa.saraf@rediffmail.com
65000   ORD28880    Chennai   750.81     3.8       unnati.jaggi@hotmail.com
70000   ORD52725    Chennai  1554.58     4.0  gautam.shankar@rediffmail.com
75000   ORD93926    Kolkata  1260.75     1.1    quincy.malhotra@hotmail.com
80000    ORD4063    Lucknow  1063.18     4.4     harrison.varma@outlook.com
85000   ORD35778     Jaipur   467.83     2.8           nitesh.lad@yahoo.com
90000   ORD12862    Chennai   503.94     3.3      kavya.dhillon@hotmail.com
95000   ORD97741    Kolkata   546.72     2.4        indrajit.gala@gmail.com
100000  ORD48867  Hyderabad  1407.61     4.7       alka.peri@rediffmail.com
105000  ORD61902    Kolkata  1090.48     3.5         yash.sawhney@gmail.com

In [66]:
df.loc[0:100000:10000,0::2]

TypeError: cannot do slice indexing on Index with these indexers [0] of type int