In [1]:
import pandas as pd

In [3]:
data = pd.read_csv("C:\\Users\\Dell\\Downloads\\22. messy_sales_data.csv")

In [4]:
df = data.copy()

In [5]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [6]:
df[df["City"] == "DELHI"]

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
33,ORD47671,CUST01447,Urvashi Andra,DELHI,Sports,UPI,639.45,1.0,5,1.3,28 Sep 2024,31.0,urvashi.andra@outlook.com,9282125480,NaN
150,ORD42630,CUST06325,Udarsh Dugar,DELHI,Beauty,Cash on Delivery,398.71,3.0,15,3.4,07/07/2023,31.0,udarsh.dugar@hotmail.com,9338086875,Superb!!! fast delivery
186,ORD78510,CUST05437,Manthan Bala,DELHI,Furniture,DC,1792.42,1.0,0,2.3,2023-10-21,37.0,manthan.bala@rediffmail.com,+91-9902364241,Packaging was bad
245,ORD26889,CUST07157,Samesh Sachdeva,DELHI,Groceries,Upi,1853.83,1.0,15,3.0,2024-01-02,53.0,samesh.sachdeva@outlook.com,NaN,Good product loved it
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106098,ORD14028,CUST02321,Chavvi Patel,DELHI,beauty,NET BANKING,4197.81,1.0,0,4.5,06-05-2023,43.0,chavvi.patel@yahoo.com,9191825127,NaN
106240,ORD24495,CUST02612,zaitra sidhu,DELHI,Beauty,dc,1456.90,3.0,20,2.5,2024-03-24,23.0,zaitra.sidhu@yahoo.com,9950252017,Excellent!!! will buy again
106296,ORD11566,CUST05883,Ubika Bawa,DELHI,Sports,Upi,2123.62,3.0,20,2.3,2023-09-07,46.0,ubika.bawa@rediffmail.com,9472236421,Not satisfied poor quality
106337,ORD63042,CUST05405,Inaya Srinivasan,DELHI,TOYS,Cash on Delivery,1077.61,1.0,0,3.3,NaN,26.0,inaya.srinivasan@rediffmail.com,9654795581,Superb!!! fast delivery
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,11/09/2024,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality

In [7]:
df[(df["City"] == "DELHI" )| (df["Quantity"] < 3)]

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
5,ORD24549,CUST07636,Ishaan Nair,New Delhi,CLOTHING,Debit Card,1271.25,1.0,0,2.8,03/26/2023,32.0,NaN,9755091854,great service
6,ORD33523,CUST02017,Tara Nagarajan,new delhi,Clothing,credit_card,1349.31,1.0,0,NaN,12-12-2023,34.0,tara.nagarajan@yahoo.com,9759730420,delivery was late
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106568,ORD105705,CUST01474,Fiyaz Chawla,Jaipur,TOYS,credit_card,1048.24,1.0,20,8.5,02 Sep 2023,38.0,fiyaz.chawla@hotmail.com,9913054504,worst product ever received damaged item
106571,ORD60012,CUST01826,CHARAN MANNE,pune,Toys,Cash on Delivery,Rs.1468.22,2.0,20,3.3,22 Apr 2024,43.0,charan.manne@yahoo.com,9226831132,Good product loved it
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,11/09/2024,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality
106573,ORD68225,CUST04602,Ladli Nazareth,AHMEDABAD,electronic,DEBIT CARD,916.52,1.0,25,4.6,19/12/2024,50.0,NaN,9914721436,NaN
106574,ORD72531,CUST07969,Yatin Rao,Chennai,Sport,DEBIT CARD,891.46,2.0,5,4.3,2024-09-29,32.0,yatin.rao@gmail.com,9438589142,Superb!!! fast delivery

In [8]:
df[(df["City"] == "DELHI" ) & (df["Quantity"] < 3)]

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
33,ORD47671,CUST01447,Urvashi Andra,DELHI,Sports,UPI,639.45,1.0,5,1.3,28 Sep 2024,31.0,urvashi.andra@outlook.com,9282125480,NaN
186,ORD78510,CUST05437,Manthan Bala,DELHI,Furniture,DC,1792.42,1.0,0,2.3,2023-10-21,37.0,manthan.bala@rediffmail.com,+91-9902364241,Packaging was bad
245,ORD26889,CUST07157,Samesh Sachdeva,DELHI,Groceries,Upi,1853.83,1.0,15,3.0,2024-01-02,53.0,samesh.sachdeva@outlook.com,NaN,Good product loved it
303,ORD33661,CUST08810,Fariq Aurora,DELHI,Groceries,credit card,406.52,1.0,0,2.7,08-03-2023,47.0,fariq.aurora@yahoo.com,9387964015,NaN
359,ORD7090,CUST01642,Lakshit More,DELHI,book,cash on delivery,1282.98,1.0,0,3.1,09-06-2024,56.0,NaN,9961010830,Packaging was bad
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106072,ORD47523,CUST05339,Atharv Suri,DELHI,grocery,Net Banking,1372.48,1.0,10,7.3,31 Mar 2024,33.0,atharv.suri@gmail.com,9567993253,NaN
106096,ORD2566,CUST02550,CHANDANI SAHOTA,DELHI,Grocery,CC,2125.07,1.0,15,4.4,04-02-2023,65.0,chandani.sahota@hotmail.com,9556395881,Good product loved it
106098,ORD14028,CUST02321,Chavvi Patel,DELHI,beauty,NET BANKING,4197.81,1.0,0,4.5,06-05-2023,43.0,chavvi.patel@yahoo.com,9191825127,NaN
106337,ORD63042,CUST05405,Inaya Srinivasan,DELHI,TOYS,Cash on Delivery,1077.61,1.0,0,3.3,NaN,26.0,inaya.srinivasan@rediffmail.com,9654795581,Superb!!! fast delivery
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,11/09/2024,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality

In [9]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [10]:
df["DiscountPct"].unique()

array([10, 20,  0,  5, 25, 15], dtype=int64)

In [11]:
df["DiscountPct"].dtypes

dtype('int64')

In [12]:
df["Rating"].unique()

array([3.3, 5. , 4.9, 2.9, 3.7, 2.8, nan, 2.4, 1.1, 1.9, 4.5, 1.8, 3.2,
       1.7, 3.4, 3. , 2.1, 4.8, 3.1, 3.5, 3.6, 1.6, 2.2, 0.5, 3.9, 1.3,
       4.1, 4. , 1.4, 2.6, 4.4, 4.6, 4.7, 4.3, 2.5, 2.3, 5.6, 0.8, 2. ,
       1.5, 7.8, 3.8, 0.7, 2.7, 0.9, 4.2, 1.2, 9.4, 9.3, 8. , 0.6, 8.9,
       1. , 8.1, 7.6, 9.6, 6.8, 7.1, 8.3, 5.8, 5.5, 7. , 7.9, 6.4, 9.2,
       8.2, 8.7, 8.5, 7.7, 6.1, 9.5, 7.3, 6.2, 9.8, 7.2, 5.9, 9.9, 5.7,
       9. , 6.7, 6.5, 6.6, 6. , 8.6, 6.3, 7.5, 9.1, 8.8, 9.7, 8.4, 6.9,
       7.4])

In [13]:
df["Rating"].dtypes

dtype('float64')

In [14]:
df["Rating"].isna().sum()

6446

In [15]:
df[["Price", "Rating"]].sample(20)

            Price  Rating
17660      485.98     2.3
19706     1522.87     2.5
3174       484.30     4.1
44567      771.81     3.1
33107     1656.01     1.9
32110     1883.41     1.9
38405     1215.47     5.9
62432     ₹831.23     3.9
36409     ₹652.24     3.9
66926      836.12     3.2
32784      973.53     3.5
87286     1241.69     4.1
54282      956.66     2.0
79504      690.99     3.2
19132     ₹513.78     3.8
7067      1181.31     1.5
101184    1363.12     3.4
81737   Rs.401.46     2.9
49371     1704.42     6.4
103693     832.14     3.7

In [16]:
df["Rating"]= df["Rating"].ffill()

#df["Rating"].bfill()

In [17]:
df["Rating"].isnull().sum()

0

In [18]:
df["OrderDate"].unique()

array(['2023-04-24', '04-01-2023', '11/17/2024', ..., '2024-05-30',
       '30 Jul 2024', '2024-12-19'], dtype=object)

In [19]:
pd.to_datetime("OrderDate",errors='coerce')

NaT

In [20]:
df['OrderDate'].isnull().sum()

4217

In [21]:
df.dropna(thresh = 5)

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,04-01-2023,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,11/17/2024,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,NaN,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,14 Jan 2023,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106570,ORD49057,CUST01636,MAX OM,chennai,FURNITURE,debit card,Rs.1961.37,4.0,0,5.0,2023-06-11,32.0,max.om@outlook.com,9123457578,Amazing quality!!!
106571,ORD60012,CUST01826,CHARAN MANNE,pune,Toys,Cash on Delivery,Rs.1468.22,2.0,20,3.3,22 Apr 2024,43.0,charan.manne@yahoo.com,9226831132,Good product loved it
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,11/09/2024,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality
106573,ORD68225,CUST04602,Ladli Nazareth,AHMEDABAD,electronic,DEBIT CARD,916.52,1.0,25,4.6,19/12/2024,50.0,NaN,9914721436,NaN
106574,ORD72531,CUST07969,Yatin Rao,Chennai,Sport,DEBIT CARD,891.46,2.0,5,4.3,2024-09-29,32.0,yatin.rao@gmail.com,9438589142,Superb!!! fast delivery

In [22]:
df['OrderDate'].dropna()

0          2023-04-24
1          04-01-2023
2          11/17/2024
4         14 Jan 2023
5          03/26/2023
             ...
106570     2023-06-11
106571    22 Apr 2024
106572     11/09/2024
106573     19/12/2024
106574     2024-09-29
Name: OrderDate, Length: 102358, dtype: object

In [23]:
df['OrderDate'].dropna().unique()[:10]

array(['2023-04-24', '04-01-2023', '11/17/2024', '14 Jan 2023',
       '03/26/2023', '12-12-2023', '11 Dec 2024', '03/24/2024',
       '09/11/2023', '01/08/2023'], dtype=object)

In [24]:
df['OrderDate'] =  pd.to_datetime(df['OrderDate'], errors='coerce', dayfirst=True)

C:\Users\Dell\AppData\Local\Temp\ipykernel_27288\11071403.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['OrderDate'] =  pd.to_datetime(df['OrderDate'], errors='coerce', dayfirst=True)

In [25]:
df['OrderDate'].unique()

<DatetimeArray>
['2023-04-24 00:00:00',                 'NaT', '2024-12-11 00:00:00',
 '2024-04-17 00:00:00', '2024-07-13 00:00:00', '2024-11-11 00:00:00',
 '2024-03-05 00:00:00', '2024-07-24 00:00:00', '2024-01-06 00:00:00',
 '2024-09-29 00:00:00',
 ...
 '2024-01-05 00:00:00', '2024-11-03 00:00:00', '2024-09-15 00:00:00',
 '2024-09-23 00:00:00', '2023-03-17 00:00:00', '2024-04-28 00:00:00',
 '2023-10-30 00:00:00', '2024-02-04 00:00:00', '2024-05-30 00:00:00',
 '2024-12-19 00:00:00']
Length: 732, dtype: datetime64[ns]

In [26]:
df['OrderDate'].isna().sum()

85892

In [27]:
median_date = df['OrderDate'].median()

In [28]:
median_date

Timestamp('2024-01-02 00:00:00')

In [29]:
df['OrderDate'] = df['OrderDate'].fillna(median_date)
df['OrderDate'].dtype

dtype('<M8[ns]')

In [30]:
df['OrderDate'].isna().sum()

0

In [31]:
df.head()

,OrderID,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,2024-01-02,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,2024-01-02,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,2024-01-02,41.0,pranit.contractor@rediffmail.com,9235766629,NaN
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,2024-01-02,44.0,hemang.chakraborty@outlook.com,9731250657,Superb!!! fast delivery

In [32]:
df["CustomerAge"].unique()

array([ 29.,  38.,  40.,  41.,  44.,  32.,  34.,  43.,  36.,  69.,  42.,
        56.,  22.,  39., 133.,  37.,  26.,  30.,  35.,  46.,  31.,  48.,
        49.,  18.,  47.,  50.,  53.,  57.,  54.,  23., 139.,  45.,  64.,
        51.,   8.,  25.,  55.,  27.,  60.,  24., 120.,  52.,   0.,  28.,
        63.,  58.,   5.,  59.,  21.,  20.,  66.,  70.,  19.,  33., 150.,
        62.,  65.,  68., 105.,  61.,  67.,  73.,  75.,  72.,  71.,  74.])

In [33]:
df["CustomerAge"] = df["CustomerAge"].astype("str")

In [34]:
df["CustomerAge"].str.replace(105.0, 100)

TypeError: repl must be a string or callable

In [35]:
df["CustomerAge"].unique()

array(['29.0', '38.0', '40.0', '41.0', '44.0', '32.0', '34.0', '43.0',
       '36.0', '69.0', '42.0', '56.0', '22.0', '39.0', '133.0', '37.0',
       '26.0', '30.0', '35.0', '46.0', '31.0', '48.0', '49.0', '18.0',
       '47.0', '50.0', '53.0', '57.0', '54.0', '23.0', '139.0', '45.0',
       '64.0', '51.0', '8.0', '25.0', '55.0', '27.0', '60.0', '24.0',
       '120.0', '52.0', '0.0', '28.0', '63.0', '58.0', '5.0', '59.0',
       '21.0', '20.0', '66.0', '70.0', '19.0', '33.0', '150.0', '62.0',
       '65.0', '68.0', '105.0', '61.0', '67.0', '73.0', '75.0', '72.0',
       '71.0', '74.0'], dtype=object)

In [36]:
df["CustomerAge"] = df["CustomerAge"].str.replace("105.0", "100")

In [37]:
df['ReviewText'].unique()

array(['Packaging was bad', '  great service  ', 'Okayish product', nan,
       'Superb!!! fast delivery', 'delivery was late',
       'worst product ever received damaged item', 'Average experience',
       'Not satisfied  poor quality', 'value for money',
       'Good product loved it', 'Excellent!!! will buy again',
       'Will not recommend', 'Product as described', 'Amazing quality!!!'],
      dtype=object)

In [38]:
df['ReviewText'] = df['ReviewText'].fillna('No Review').str.strip()

In [39]:
df['ReviewText'] = df['ReviewText'].str.replace(r'!{2,}', '!', regex=True)

In [40]:
df['ReviewText'].unique()

array(['Packaging was bad', 'great service', 'Okayish product',
       'No Review', 'Superb! fast delivery', 'delivery was late',
       'worst product ever received damaged item', 'Average experience',
       'Not satisfied  poor quality', 'value for money',
       'Good product loved it', 'Excellent! will buy again',
       'Will not recommend', 'Product as described', 'Amazing quality!'],
      dtype=object)

In [41]:
df.rename(columns= {'OrderID':'order_id'})

,order_id,CustomerID,CustomerName,City,Category,PaymentMode,Price,Quantity,DiscountPct,Rating,OrderDate,CustomerAge,Email,Phone,ReviewText
0,ORD51058,CUST04879,Chaitanya Mane,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,29.0,chaitanya.mane@gmail.com,9454663439,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,2024-01-02,38.0,NaN,NaN,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,chennai,electronic,Upi,770.67,1.0,0,4.9,2024-01-02,40.0,nathaniel.chatterjee@outlook.com,9573975601,Okayish product
3,ORD46367,CUST07605,pranit contractor,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,2024-01-02,41.0,pranit.contractor@rediffmail.com,9235766629,No Review
4,ORD32922,CUST03180,Hemang Chakraborty,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,2024-01-02,44.0,hemang.chakraborty@outlook.com,9731250657,Superb! fast delivery
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106570,ORD49057,CUST01636,MAX OM,chennai,FURNITURE,debit card,Rs.1961.37,4.0,0,5.0,2023-06-11,32.0,max.om@outlook.com,9123457578,Amazing quality!
106571,ORD60012,CUST01826,CHARAN MANNE,pune,Toys,Cash on Delivery,Rs.1468.22,2.0,20,3.3,2024-01-02,43.0,charan.manne@yahoo.com,9226831132,Good product loved it
106572,ORD78050,CUST04033,Isaiah Wali,DELHI,Furniture,Debit Card,414.94,2.0,10,3.3,2024-01-02,23.0,isaiah.wali@hotmail.com,9758098090,Not satisfied poor quality
106573,ORD68225,CUST04602,Ladli Nazareth,AHMEDABAD,electronic,DEBIT CARD,916.52,1.0,25,4.6,2024-01-02,50.0,NaN,9914721436,No Review
106574,ORD72531,CUST07969,Yatin Rao,Chennai,Sport,DEBIT CARD,891.46,2.0,5,4.3,2024-09-29,32.0,yatin.rao@gmail.com,9438589142,Superb! fast delivery

In [42]:
df = df.rename(columns={
    'OrderID':'order_id','CustomerID':'customer_id','CustomerName':'customer_name',
    'City':'city','Category':'category','PaymentMode':'payment_mode',
    'Price':'price','Quantity':'quantity','DiscountPct':'discount_pct',
    'Rating':'rating','OrderDate':'order_date','CustomerAge':'customer_age',
    'Email':'email','Phone':'phone','ReviewText':'review_text'
})

In [43]:
df.columns

Index(['order_id', 'customer_id', 'customer_name', 'city', 'category',
       'payment_mode', 'price', 'quantity', 'discount_pct', 'rating',
       'order_date', 'customer_age', 'email', 'phone', 'review_text'],
      dtype='object')

In [44]:
col_order = ['order_id','customer_id','customer_name','customer_age','email','phone',
             'city','category','payment_mode','price','quantity','discount_pct',
             'rating','order_date','review_text']

df = df[col_order]

df.head()

,order_id,customer_id,customer_name,customer_age,email,phone,city,category,payment_mode,price,quantity,discount_pct,rating,order_date,review_text
0,ORD51058,CUST04879,Chaitanya Mane,29.0,chaitanya.mane@gmail.com,9454663439,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,38.0,NaN,NaN,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,2024-01-02,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,40.0,nathaniel.chatterjee@outlook.com,9573975601,chennai,electronic,Upi,770.67,1.0,0,4.9,2024-01-02,Okayish product
3,ORD46367,CUST07605,pranit contractor,41.0,pranit.contractor@rediffmail.com,9235766629,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,2024-01-02,No Review
4,ORD32922,CUST03180,Hemang Chakraborty,44.0,hemang.chakraborty@outlook.com,9731250657,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,2024-01-02,Superb! fast delivery

In [45]:
df1 = df[['order_id','quantity','discount_pct','rating']]

In [46]:
df1.head()

   order_id  quantity  discount_pct  rating
0  ORD51058       3.0            10     3.3
1  ORD70248       4.0            20     5.0
2  ORD43804       1.0             0     4.9
3  ORD46367       1.0             0     2.9
4  ORD32922       4.0            10     3.7

In [47]:
df = df.reset_index(drop=True)

df.index.name = 'row_no'

df.head()

,order_id,customer_id,customer_name,customer_age,email,phone,city,category,payment_mode,price,quantity,discount_pct,rating,order_date,review_text
row_no,,,,,,,,,,,,,,,
0,ORD51058,CUST04879,Chaitanya Mane,29.0,chaitanya.mane@gmail.com,9454663439,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,38.0,NaN,NaN,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,2024-01-02,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,40.0,nathaniel.chatterjee@outlook.com,9573975601,chennai,electronic,Upi,770.67,1.0,0,4.9,2024-01-02,Okayish product
3,ORD46367,CUST07605,pranit contractor,41.0,pranit.contractor@rediffmail.com,9235766629,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,2024-01-02,No Review
4,ORD32922,CUST03180,Hemang Chakraborty,44.0,hemang.chakraborty@outlook.com,9731250657,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,2024-01-02,Superb! fast delivery

In [48]:
df1.reset_index("order_id")

KeyError: 'Requested level (order_id) does not match index name (None)'

In [49]:
df.head()

,order_id,customer_id,customer_name,customer_age,email,phone,city,category,payment_mode,price,quantity,discount_pct,rating,order_date,review_text
row_no,,,,,,,,,,,,,,,
0,ORD51058,CUST04879,Chaitanya Mane,29.0,chaitanya.mane@gmail.com,9454663439,bangalore,Grocery,net_banking,904.48,3.0,10,3.3,2023-04-24,Packaging was bad
1,ORD70248,CUST00177,Siddharth Sha,38.0,NaN,NaN,DELHI,SPORTS,Net Banking,1823.76,4.0,20,5.0,2024-01-02,great service
2,ORD43804,CUST04537,Nathaniel Chatterjee,40.0,nathaniel.chatterjee@outlook.com,9573975601,chennai,electronic,Upi,770.67,1.0,0,4.9,2024-01-02,Okayish product
3,ORD46367,CUST07605,pranit contractor,41.0,pranit.contractor@rediffmail.com,9235766629,Jaipur,Clothing,COD,2028.06,1.0,0,2.9,2024-01-02,No Review
4,ORD32922,CUST03180,Hemang Chakraborty,44.0,hemang.chakraborty@outlook.com,9731250657,Amdavad,FURNITURE,cc,604.00,4.0,10,3.7,2024-01-02,Superb! fast delivery

In [50]:
import pandas as pd

In [ ]:
data.to_excel("filename.xlsx")

In [ ]:
data.to_excel("filename.json")